### ISSUE TITLE
关于写入长度超过buffer容量的处理

### ISSUE THREAD

**Issue by freecw** [guoanwu/pmem_program#1]
if(aofguard->buffer.len + len > aofguard->buffer.capacity)
    {
        if((aofguard->buffer.len % BLOCK_SIZE) + len > aofguard->buffer.capacity)
            ERROR(0, 1, "param <len = %lu> is too big to write atomicly!", len);
        if(!wait_afsync_done(aofguard))
            ERROR(0, 0, "wait_afsyc_done(aofguard) failed!");
        if(aofguard->buffer.len + len > aofguard->buffer.capacity && !do_fsync(aofguard))
            ERROR(0, 0, "do_fsync(aofguard) failed!");
    }

关于这段逻辑，不太理解为什么wait_afsync_done(aofguard)结束之后，还会有aofguard->buffer.len + len > aofguard->buffer.capacity的情况。另外，程序似乎没有做异步刷盘线程出错退出的异常处理

**Comment by guoanwu** [comment]
谢谢你的评论，有可能异步写失败的话，还可以做一次同步写。 嗯，线程出错没有考虑。

**Comment by freecw** [comment]
我理解应该是aofguard_init将ring buffer的内容添加到file之后，如果继续来了一个很大的写，有可能会超过buffer的capacity，这个do_fsync应该是处理这个情况。因为这时候是没有异步线程写的。
